# Usar una imagen base de Python
FROM python:3.8

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código al contenedor
COPY . /app

# Instalar dependencias (aquí puedes añadir cualquier otra librería que necesites)
RUN pip install --no-cache-dir pandas numpy IPython

# Ejecutar script de Python cuando se inicie el contenedor
CMD ["python", "./scripts/Data_preprocess.py"]
